### ISSUE TITLE
Server doesn't seem to respond and world doesn't load after entering End portal

### ISSUE THREAD

**Issue by benji78** [cally72jhb/vector-addon#33]
I have used this addon with no problem for the last month, until I went through the End portal after the dragon fight. Note that the End portal in the overworld taking me to the End works fine with vector enabled, it really is just getting back to the overworld from the End.
I have quite a few mods so it took me a while to figure out which one was the culprit, but now that I have only vector disabled, I can go through the End portal and the overworld loads almost instantly.

What's happening is that as soon I jump into the portal I get a "server is lagging" pop-up for exactly 1 second every second, while I can continue to move around the End as though there were no portal, but I can't interact with chests or anything.
If I disconnect and try to log back in, I get stuck on "loading terrain" for an average of 10 seconds after which I am bobing at the coordinates 1,0,1 (in the End, because although nothing loads distantHorizons still works). However if I enable and disable fly, I fall endlessly (no void). I can still fly around (without any way to get fly kicked and there is nothing I can do. The only way I found to get out is to disable vector, at which point I spawn at my bed.

I am very confused by this bug !

**Comment by benji78** [comment]
I also had problems when trying out Portal God Mode, but I don't remember what it was.

**Comment by fireblade2534** [comment]
enable antiscreen and disable end screen

**Comment by cally72jhb** [comment]
I believe that you might have PortalGodMode enabled

PortalGodMode makes it so that you are invincible after entering a portal, but cannot move or interact with blocks, nor see entities but you can still break blocks.
On the client-side it therefore seems as if you are moving while on server-side you're not. This also applies to what you described about flight and the server not responding. Basically you are desynced from the server for serveral reasons (the main one beeing PortalGodMode) and need to relog to fix this.

Turning off PortalGodMode could be a solution, but there could also be interference between vectors mixins (not the current version as I just checked) and the various mods you use.

PS
Sorry for the late response, I took some time off mc
I hope I could still help you with this

PS 2
Are you playing in singleplayer? If you are it might be stupid to use meteor because it is made for servers and it's mixins might change how the local server works, especially the ones that modify shared code for the server & client.

**Comment by GoofyBoi420** [comment]
another solution is to use anti screen
